"""
RunProof Model

Represents a validation proof generated by the @validator decorator.
Each proof contains:
- Input/output hashes for integrity
- Execution metadata (time, status)
- Cryptographic signature for authenticity
- Sync status for cloud integration
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field
import hashlib
import json


class ProofStatus(str, Enum):
    """Status of a validation proof."""
    CREATED = "created"
    VALIDATED = "validated"
    SYNCED = "synced"
    FAILED = "failed"


class RunProof(BaseModel):
    """
    A validation proof generated by the RunLayer SDK.
    
    Each proof represents a single execution of a validated function,
    containing all necessary information to verify the validation
    independently and cryptographically.
    """
    
    # Unique identifier
    id: str = Field(..., description="Unique proof identifier")
    
    # Validator information
    validator_name: str = Field(..., description="Name of the validator function")
    validator_version: str = Field(..., description="Semantic version of the validator")
    
    # Input/output integrity
    input_hash: str = Field(..., description="SHA-256 hash of input data")
    output_hash: str = Field(..., description="SHA-256 hash of output data")
    
    # Execution data
    input_data: Any = Field(..., description="Original input data")
    output_data: Any = Field(..., description="Validation result")
    execution_time_ms: int = Field(..., description="Execution time in milliseconds")
    
    # Metadata
    status: ProofStatus = Field(default=ProofStatus.CREATED, description="Current proof status")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Creation timestamp")
    workspace_id: str = Field(..., description="Workspace identifier")
    
    # Cryptographic signature
    signature: Optional[str] = Field(None, description="Ed25519 signature of proof data")
    
    # Sync tracking
    synced_to_cloud: bool = Field(default=False, description="Whether proof is synced to cloud")
    sync_timestamp: Optional[datetime] = Field(None, description="Last sync timestamp")
    
    # Additional metadata
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional proof metadata")
    
    class Config:
        """Pydantic configuration."""
        json_encoders = {
            datetime: lambda v: v.isoformat(),
        }
        
    @classmethod
    def create_proof(
        cls,
        validator_name: str,
        validator_version: str,
        input_data: Any,
        output_data: Any,
        execution_time_ms: int,
        workspace_id: str,
        metadata: Optional[Dict[str, Any]] = None
    ) -> "RunProof":
        """
        Create a new RunProof from validation execution.
        
        Args:
            validator_name: Name of the validator function
            validator_version: Semantic version of the validator
            input_data: Original input to the validator
            output_data: Result from the validator
            execution_time_ms: Execution time in milliseconds
            workspace_id: Workspace identifier
            metadata: Additional metadata
            
        Returns:
            New RunProof instance with computed hashes and ID
        """
        # Generate hashes
        input_hash = cls._hash_data(input_data)
        output_hash = cls._hash_data(output_data)
        
        # Generate unique ID from validator and input hash
        proof_id = cls._generate_proof_id(validator_name, validator_version, input_hash)
        
        return cls(
            id=proof_id,
            validator_name=validator_name,
            validator_version=validator_version,
            input_hash=input_hash,
            output_hash=output_hash,
            input_data=input_data,
            output_data=output_data,
            execution_time_ms=execution_time_ms,
            workspace_id=workspace_id,
            metadata=metadata or {}
        )
    
    @staticmethod
    def _hash_data(data: Any) -> str:
        """
        Generate SHA-256 hash of data.
        
        Args:
            data: Data to hash
            
        Returns:
            Hexadecimal hash string
        """
        # Convert data to JSON string for consistent hashing
        json_str = json.dumps(data, sort_keys=True, default=str)
        return hashlib.sha256(json_str.encode()).hexdigest()
    
    @staticmethod
    def _generate_proof_id(validator_name: str, validator_version: str, input_hash: str) -> str:
        """
        Generate unique proof ID.
        
        Args:
            validator_name: Name of the validator
            validator_version: Version of the validator
            input_hash: Hash of the input data
            
        Returns:
            Unique proof identifier
        """
        # Combine validator info and input hash for uniqueness
        combined = f"{validator_name}:{validator_version}:{input_hash}"
        return hashlib.sha256(combined.encode()).hexdigest()[:16]
    
    def to_dict(self) -> Dict[str, Any]:
        """
        Convert proof to dictionary for storage/transmission.
        
        Returns:
            Dictionary representation of the proof
        """
        return self.dict()
    
    def get_signature_data(self) -> str:
        """
        Get the data that should be signed for cryptographic verification.
        
        Returns:
            JSON string of core proof data for signing
        """
        signature_data = {
            "id": self.id,
            "validator_name": self.validator_name,
            "validator_version": self.validator_version,
            "input_hash": self.input_hash,
            "output_hash": self.output_hash,
            "execution_time_ms": self.execution_time_ms,
            "created_at": self.created_at.isoformat(),
            "workspace_id": self.workspace_id
        }
        return json.dumps(signature_data, sort_keys=True)
    
    def is_valid(self) -> bool:
        """
        Validate proof integrity.
        
        Returns:
            True if proof hashes match the data
        """
        try:
            # Verify input hash
            computed_input_hash = self._hash_data(self.input_data)
            if computed_input_hash != self.input_hash:
                return False
            
            # Verify output hash
            computed_output_hash = self._hash_data(self.output_data)
            if computed_output_hash != self.output_hash:
                return False
            
            # Verify proof ID
            computed_id = self._generate_proof_id(
                self.validator_name, 
                self.validator_version, 
                self.input_hash
            )
            if computed_id != self.id:
                return False
            
            return True
        except Exception:
            return False
    
    def mark_synced(self) -> None:
        """Mark proof as synced to cloud."""
        self.synced_to_cloud = True
        self.sync_timestamp = datetime.utcnow()
        self.status = ProofStatus.SYNCED
    
    def mark_failed(self) -> None:
        """Mark proof as failed."""
        self.status = ProofStatus.FAILED
